image: gcc

build:
  tags:
    - rhel7
  stage: build
  #before_script:
  #  - apt-get update && apt-get -y install cmake liblog4cxx10-dev libboost-program-options-dev libboost-filesystem-dev libboost-date-time-dev libboost-system-dev libboost-test-dev libboost-thread-dev libboost-regex-dev libzmq3-dev libpcap-dev
  variables:
    HDF5_ROOT: /dls_sw/prod/tools/RHEL7-x86_64/hdf5/1-10-4/prefix
    BLOSC_ROOT: /dls_sw/prod/tools/RHEL7-x86_64/c-blosc/1-14-2/prefix
    INSTALL_PREFIX: $CI_PROJECT_DIR/install_prefix
    ODIN_PREFIX: $CI_PROJECT_DIR/odin-data-integration-test
    LOG4CXX_ROOT: /dls_sw/prod/tools/RHEL7-x86_64/log4cxx/0-10-0dls2/prefix
    HDF5_PLUGIN_PATH: /dls_sw/work/tools/RHEL6-x86_64/hdf5filters/prefix/h5plugin
    META_LISTENER_ROOT: /dls_sw/prod/tools/RHEL7-x86_64/defaults/bin
    PYTHONPATH: $CI_PROJECT_DIR/data/tools/python/:$CI_PROJECT_DIR/odin-data/tools/python
  script:
    - bash .install-odin.sh
    - mkdir -p buildfolder
    - mkdir -p $INSTALL_PREFIX
    - cd buildfolder
    - cmake -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DODINDATA_ROOT_DIR=$ODIN_PREFIX -DLOG4CXX_ROOT_DIR=$LOG4CXX_ROOT ../data
    - cmake --build . --target install
    - cd ..
    - $ODIN_PREFIX/bin/odinDataTest --json=$INSTALL_PREFIX/test_config/eiger.json
    - $INSTALL_PREFIX/bin/eigerfan-test
