# Use controls group runners unless overridden in jobs
default:
  tags:
    - controls

stages:
  - build
  - deploy

wheel:
  stage: build
  image: python:3.7
  script:
    - cd ${CI_PROJECT_DIR}/python/
    - pip install build 'pipenv==2021.5.29'
    - python -m build --wheel --outdir dist/
    - python -m pipenv --python 3.7 lock -v --pypi-mirror https://pypiserver.diamond.ac.uk && mv Pipfile.lock dist/
  artifacts:
    paths:
      - python/dist/

deploy_dist:
  stage: deploy
  image: python:3.7
  script:
    - cp python/dist/*whl /dls_sw/work/python3/RHEL7-x86_64/distributions
    - cp python/dist/Pipfile.lock /dls_sw/work/python3/RHEL7-x86_64/distributions/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.Pipfile.lock
    - echo "Run 'dls-release.py -t -a python3ext ${CI_PROJECT_NAME} ${CI_COMMIT_TAG}' to release to python3 area"
  only:
    - tags
