language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - liblog4cxx10-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-date-time-dev
        - libboost-dev
        - libboost-system-dev
        - libboost-test-dev
        - libboost-thread-dev
        - libzmq3-dev
        - libpcap-dev
        - libboost-regex-dev
    env: HDF5_ROOT=$HOME/hdf5-1.10.1 INSTALL_PREFIX=$HOME/install_prefix ODIN_PREFIX=$HOME/odin-data BLOSC_ROOT=$HOME/c-blosc-1.14.2 KAFKA_ROOT=$HOME/librdkafka-1.0.0 PYTHONPATH=$HOME/build/dls-controls/eiger-detector/data/tools/python:$HOME/odin-data/tools/python META_LISTENER_ROOT=$HOME/.local/bin HDF5_PLUGIN_PATH=$HOME/hdf5filters/h5plugin
    before_install:
    - bash .travis-install-blosc.sh
    - bash .travis-install-librdkafka.sh
    - bash .travis-install-hdf5.sh
    - bash .travis-install-odin.sh
    - bash .travis-install-hdf5filters.sh
install:
- git fetch --depth=500
- mkdir -p build
- mkdir -p $INSTALL_PREFIX
- cd build;
- cmake -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX -DODINDATA_ROOT_DIR=$ODIN_PREFIX ../data;
- cmake --build . --target install;
- cd ..
script:
- ${ODIN_PREFIX}/bin/odinDataTest --json=${INSTALL_PREFIX}/test_config/eiger-tr.json
- $INSTALL_PREFIX/bin/eigerfan-test
after_success:
- coveralls
notifications:
  slack:
    secure: Svf3MGnsFL8FYwODLfRl8AYJNQkK4WmdDtvByF2dhIeJ5R1HqN4wxHNWv9L0vAiwQh4JKSrCNK8gBGMpSAmgeuBmiC7JSUHZEIDinVx01KC66drAz1p9c7nF+Plw3mr9Uq8PTCZ6rL0SDxcw/EYP1EaBOOB+IijmZumdbNaDCUp474jBcxhW1gJFuMiRm/8w3eukaYGyUA7I1jpkh2eK7DHZzbaBUgFVfrttMexNBjHsqEClXobcWSFJqhA37ZYSFTdRwYVGpMpnIOzxgmmncN+lnzL1to5U5DK6/mhYCqiDboyaVBjYmL+ffCDxqDaR7JX7IzjL/d2brfrHLMGJxMwCDG0mXx7REia1TicxpsrOohiU3bJ9HXVrxAhSGXjr4CS3AIixGOLsA51XkDtxUumLZMz2eJXKCGhw2ZI0Apb3mrKflIa8OEklPVQoD2omqOgSUmEBNnkyFjs8RqGfWRbdXOela3BMqvvQSqlyL5IinlbrluA06JDWKpXllpz+SKlb5mRGtR84KlI6uRHD95oTw+SwfS+ai94aLcbgsojhOFg1nGhhphnyqfUSYekhr/REyNgY61cAVy+1tJ/pQSVIjhVJidl/HBmWousCPQxhmxUkxeb7lQlR+ORNYQ76/UP36uzOlitRGhAHumaw4VvZG2fMDOduKzuwF+2qjIQ=
